### PR TITLE
meta: remove brew lockfile from git tracking

### PR DESCRIPTION
**Pull request by armcknight**
after updating my local tooling to fix the issue I was experiencing in #3737 

#skip-changelog

### CODE REVIEW

**Comment by brustolin** [comment]
Can we just remove this two lock files from git?

**Review by philipphofmann — APPROVED** [review]
LGTM

**Comment by armcknight** [comment]
> Can we just remove this two lock files from git?

Honestly yeah, at this point I don't see why not. Let's try it and see what happens.

**Comment by armcknight** [comment]
@philipphofmann @brustolin please re-review the removal of the lockfiles here when you get a chance 🙏🏻

**Review by brustolin — APPROVED** [review]
No problem here.

Please just add this files to git ignore.

**Comment by philipphofmann** [comment]
I'm unsure if we should remove the lock files. They ensure we all use the same version of dependencies locally and in CI.

**Comment by brustolin** [comment]
> I'm unsure if we should remove the lock files. They ensure we all use the same version of dependencies locally and in CI.

It does not work. Every time I run `make init`, the lock files are updated.

**Comment by armcknight** [comment]
Makes sense @philipphofmann , let's give that a shot

**Pull request merged**
