### PR TITLE
docs: call out beta status for all public-facing profiling APIs

### PR DESCRIPTION
**Pull request by armcknight**
Add notes and beta warnings to all public-facing APIs for profiling.

#skip-changelog

### CODE REVIEW

**Review by philipphofmann — COMMENTED** [review]
Excellent 💯. For experimental features we have something similar, see https://github.com/getsentry/sentry-cocoa/blob/06548c0f88eefd4a54851752c7d33f4270e34ba9/Sources/Sentry/Public/SentryOptions.h#L162-L170

Do you mind aligning how we point out beta and experimental?

**Review by brustolin — APPROVED** [review]

**Comment by armcknight** [comment]
> Do you mind aligning how we point out beta and experimental?

I don't mind, but I'm not sure what you have in mind. Do you want ours to match yours, or vice-versa?

**Comment by armcknight** [comment]
> Do you mind aligning how we point out beta and experimental?

@philipphofmann I don't mind, but I'm not sure what you have in mind. Do you want ours to match yours, or vice-versa?

**Comment by philipphofmann** [comment]
> > Do you mind aligning how we point out beta and experimental?
> 
> @philipphofmann I don't mind, but I'm not sure what you have in mind. Do you want ours to match yours, or vice-versa?

I don't really mind which one, as long as it's consistent. We can also keep it as it is. Most important the we inform the users about experimental and beta features. I think for the experimental features it's important to mention that they are experimental at the beginning of the code docs.

**Comment by armcknight** [comment]
@philipphofmann I turned every note about beta/experimental features into `@warning` in objc and `- warning:` in swift headerdocs, at the beginning of whatever comment block it lives in.

**Comment by philipphofmann** [comment]
Thanks @armcknight 💯

**Pull request merged**
