### PR TITLE
fix: Solve the "Double-quoted include" warnings

### LINKED ISSUE #1072: Fix all "Double-quoted include in framework header, expected angle-bracketed instead" warnings
### Environment

How do you use Sentry?
On-premise (21.3.0)

Which SDK and version?
iOS 6.2.1

### Steps to Reproduce

1. Install Xcode 12.5
2. Create a new project or upgrade a new project's configurations to Xcode 12.5's recommended settings
3. Integrate Sentry's iOS SDK
4. Make a build

### Expected Result

There should be no warnings.

### Actual Result

Xcode 12.5 will suggest turning on by-default the following warning: CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER=YES.

```
Warns when a quoted include is used instead of a framework style include in a framework header.
```

Turning it on throws warnings for all the places the Sentry framework is using a project (quote) include instead of a framework (angle bracket) import.

### PR DESCRIPTION
**Pull request by kevinrenskers**
## :scroll: Description

Fixes all the "Double-quoted include" warnings. You could easily trigger them by building the ObjC sample app.

## :bulb: Motivation and Context

Closes #1072

## :green_heart: How did you test it?

Compiling the app and the sample apps still works, all the tests still work.

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

**Comment by kevinrenskers** [comment]
Integration tests fail on `#import <Sentry/SentryDefines.h>`. Not sure why, as locally it all works, also when building the sample apps. @brustolin any ideas?

**Comment by brustolin** [comment]
> Integration tests fail on `#import <Sentry/SentryDefines.h>`. Not sure why, as locally it all works, also when building the sample apps. @brustolin any ideas?

Nope. I tried to do this too some time ago and SPM is not happy. And this is a big deal for us.

**Comment by kevinrenskers** [comment]
Unless someone else has some insight into this I guess we close this and live with the warnings? But surely other SDKs don't generate the same kind of warnings so this should be possible to solve I would think.

**Comment by armcknight** [comment]
If we're adding the Sentry SDK directly to one of the AlamoFire example projects, you could try integrating it via CocoaPods/Carthage/SPM instead, both to see if the resultant changes still match what is in our patchfile, and to see if it passes in CI also/anyways.

Our current approach of applying a patch file is more brittle than that so seems like it'd also leave things in a better state if we did that moving forwards.

**Comment by kevinrenskers** [comment]
I've looked at integration-tests.yml and add-sentry-to-alamofire.patch, and I have a suspicion that it's already integrated with SPM? Since there's mention of a `XCRemoteSwiftPackageReference` with the URL https://github.com/getsentry/sentry-cocoa.. so I don't think we're adding the Sentry SDK directly as you said?

```
+/* Begin XCRemoteSwiftPackageReference section */
+		7B4C98B32743C1FE00B03EC9 /* XCRemoteSwiftPackageReference "sentry-cocoa" */ = {
+			isa = XCRemoteSwiftPackageReference;
+			repositoryURL = "https://github.com/getsentry/sentry-cocoa";
+			requirement = {
+				kind = revision;
+				revision = __GITHUB_REVISION_PLACEHOLDER__;
+			};
+		};
+/* End XCRemoteSwiftPackageReference section */
+
+/* Begin XCSwiftPackageProductDependency section */
+		7B4C98B42743C1FE00B03EC9 /* Sentry */ = {
+			isa = XCSwiftPackageProductDependency;
+			package = 7B4C98B32743C1FE00B03EC9 /* XCRemoteSwiftPackageReference "sentry-cocoa" */;
+			productName = Sentry;
+		};
+/* End XCSwiftPackageProductDependency section */
```

This looks similar to me as a test project I created and added sentry-cocoa via SPM.

**Comment by brustolin** [comment]
> and I have a suspicion that it's already integrated with SPM?  

Yes. The problem is not the integration, the problem is the way SPM is build. 
All you need to do is make sure `swift build` works which base on this action `Build / Build with Swift (pull_request)` is not.
I really think this worth an extra investigation, it would be nice to have this solved, but if this is taking too long we close the PR, this is definitely not a high priority.

**Comment by armcknight** [comment]
Hm, it sounds like we might need something like https://github.com/getsentry/sentry-cocoa/pull/1726 first. If SPM links Sentry statically, then framework-style imports probably won't work.

**Comment by brustolin** [comment]
> Hm, it sounds like we might need something like #1726 first. If SPM links Sentry statically, then framework-style imports probably won't work.

But even then this won't work, I think, because the static lib options will still be available

**Comment by philipphofmann** [comment]
https://github.com/getsentry/sentry-cocoa/pull/1726 was merged, @kevinrenskers can you please revisit this PR?

**Comment by kevinrenskers** [comment]
Will do

**Comment by kevinrenskers** [comment]
We're still getting fatal errors like `fatal error: 'Sentry/SentryDefines.h' file not found`.

Anyone got an idea on how to fix this? I'm really not experienced with frameworks and static/dynamic libs and how that works with SPM etc etc. 

But @brustolin did predict this:

> But even then this won't work, I think, because the static lib options will still be available

So not sure if anything can be done.

**Comment by philipphofmann** [comment]
I also don't know how to fix this right now, and sadly I don't have the bandwidth to look at this. We can also close this PR, if we can't figure it out right now.

**Pull request closed without merging**
