### PR TITLE
ci: remove TrendingMovies and profile data generation CI job

### PR DESCRIPTION
**Pull request by armcknight**
Now that the profiling feature has been GA for a while and our system is stress tested with customer traffic, and we don't use the TrendingMovies app to validate SDK changes (which we can now turn to https://github.com/sentry-demos/ios for) we can entirely remove that test app and the associated CI job from our SDK repo.

#skip-changelog

### CODE REVIEW

**Review by philipphofmann — APPROVED** [review]
LGTM

**Comment by philipphofmann** [comment]
@armcknight, the changes of this PR haven't ended up in main yet. Please open another PR.

**Comment by armcknight** [comment]
Are you sure? Should be in main after https://github.com/getsentry/sentry-cocoa/pull/3451 was merged. I don't see any of the files/directories that were deleted after updating my local clone
image

**Comment by philipphofmann** [comment]
> Should be in main after https://github.com/getsentry/sentry-cocoa/pull/3451 was merged.

Ah, I missed that one. Thanks 🥳

**Pull request merged**
