### PR TITLE
Add Swift Package Manager Support

### PR DESCRIPTION
**Pull request by JonathanDowning**
This is a possible implementation for #312 which adds support for Swift Package Manager.

Trying to get SPM working with SentryCrash's non-flat folder structure proved too difficult for me, so I opted to move all files to the root of the SentryCrash folder.
Code owners may prefer to keep the folder structure, but at the cost of a more complex Package.swift file.

There is also a potential issue in that I've needed to include SentryCrashInstallation+Private.h in the include directory, which might not be desirable, again, comments and suggestions welcome.

Whether this PR is accepted as-is, or a different implementation is used, I hope this will contribute to getting Swift Package Manager support merged as quickly as possible :)

### CODE REVIEW

**Comment by bdrelling** [comment]
What's the status of SPM integration for Sentry?

**Comment by makoni** [comment]
Any progress?

**Comment by HazAT** [comment]
So this is for sure on our radar and we want to have this, but we can't merge this PR in this shape because it restructures the whole file structure and the risk of breaking our current setup is very high.

Please stay tuned.

**Comment by fetzig** [comment]
This approach #352 looks very promising. So I'm closing this PR.

**Pull request closed without merging**
