### PR TITLE
Fix import of `User` & `Breadcrumb`

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

- Import with `""` instead of `<>`

## :bulb: Motivation and Context

Tried updating the `Dart` SDK to the most recent version and go the following error.

Bildschirmfoto 2023-05-09 um 13 56 41

Bildschirmfoto 2023-05-09 um 15 07 46

Bildschirmfoto 2023-05-09 um 15 07 33

## :green_heart: How did you test it?

- Run sample app with `""` imports.

## :pencil: Checklist

You have to check all boxes before merging:

- [x] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

## :crystal_ball: Next steps

Check if CI runs without issues.

### CODE REVIEW

**Comment by denrase** [comment]
@philipphofmann This should probably affect all users trying to use the coco sdk?

**Review by brustolin — APPROVED** [review]

**Comment by philipphofmann** [comment]
> @philipphofmann This should probably affect all users trying to use the coco sdk?

The affected file is only used for the Hybrid SDKs, if I'm not mistaken. @brustolin, can you maybe evaluate if we can do something in CI to prevent such errors in the future? It would be great to catch these errors early on.

**Comment by brustolin** [comment]
I think we can simulate the need for the hybrid SDK with cocoapod to catch this.

**Comment by brustolin** [comment]
> Would you be up for opening a PR for that, @brustolin?

Sure

**Pull request merged**
