### PR TITLE
feat: Remove SentryOptions.enabled

### PR DESCRIPTION
**Pull request by philipphofmann**
## :scroll: Description
Other SentrySDKs don't have this option. We want to align with them and remove it.
Furthermore, SentryClient now doesn't send any events or sessions if the DSN is nil.

## :bulb: Motivation and Context

Other SentrySDKs don't have this option. We want to align with them and remove it.

## :green_heart: How did you test it?
Travis.

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] I updated the CHANGELOG
- [ ] No breaking changes

### CODE REVIEW

**Review by bruno-garcia — APPROVED** [review]
Nice! deleted code replaced with testing the correct behavior!

**Comment by eric** [comment]
This is really a bummer. We relied on this to easily enable/disable sending to Sentry based on user privacy settings. It doesn't appear that there is any other mechanism we can use at runtime to enable and disable sending to Sentry.

**Comment by philipphofmann** [comment]
@eric someone already opened up a PR for this https://github.com/getsentry/sentry-cocoa/pull/700, but didn't continue with our feedback. Maybe we just grab it ourselves and finish it. You are also welcome to help us out on this one.

**Comment by lhunath** [comment]
@philipphofmann It should be noted that #700 cannot (in its current form) be used for toggling the state of Sentry based on the user's privacy preferences / consent, since it's read-only.

**Comment by eric** [comment]
Honestly the feature we’re looking for is exactly what this feature did. If I were to propose a new feature, it would be just reverting this pull request.

**Comment by lhunath** [comment]
I understand there's a rational for homogenizing the different platform SDKs, but in doing so has Sentry considered the impact that the solution of removing `enabled` has on the use case of consent management or was this effect not considered as part of this decision?  If yes, I'd be keen to hear what the conclusion was and whether there's an alternative suggestion for handling consent.  If no, I recommend that Sentry both consider consent management now and also adopts a more conscientious strategy to modifying existing API.

**Comment by philipphofmann** [comment]
@eric and @lhunath thanks a lot for your input. I opened up an issue for this. Let's move the discussion there please: https://github.com/getsentry/sentry-cocoa/issues/809 for more info.

**Pull request merged**
