### PR TITLE
feat: Report App Memory Usage

### LINKED ISSUE #999: Report App Memory Usage
Currently the amount of memory used by the app at the time of the crash isn't reported. 
We could read that and add it to the event with such snippet:

```objc
    task_vm_info_data_t info;
    mach_msg_type_number_t size = TASK_VM_INFO_COUNT;
    kern_return_t kerr = task_info(mach_task_self(),
                                   TASK_VM_INFO,
                                   (task_info_t)&info,
                                   &size);
    if( kerr == KERN_SUCCESS ) {
        mach_vm_size_t totalSize = info.internal + info.compressed;
        //Add totalSize to the event as the app memory usage.
    } 
```

### PR DESCRIPTION
**Pull request by kevinrenskers**
## :scroll: Description

Just like we're reporting free memory (see #1962), we are now reporting app memory usage.

## :bulb: Motivation and Context

Closes #999

## :green_heart: How did you test it?

Unit tests, manual test.

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

**Comment by kevinrenskers** [comment]
Screen Shot 2022-08-01 at 12 25 38

I'm not sure why "Free Memory" is shown as a human readable value, but "App Memory" is shown as a raw value. Is there a magic key I should use rather than `app_memory`?

**Comment by brustolin** [comment]
Instead of device context, we should store this information in the app context.

**Comment by kevinrenskers** [comment]
Done

**Review by armcknight — APPROVED** [review]

**Comment by bruno-garcia** [comment]
> So I guess we need to create a ticket for the backend/ui team to format this value?

Was there a follow up on this? 

This was done here: https://github.com/getsentry/sentry/pull/20909

**Comment by bruno-garcia** [comment]
Could be worth writing on the develop docs how to format data so that it's presented like that. Or where/how to change Sentry to do so (e.g: link to this PR?)

**Comment by kevinrenskers** [comment]
Dhiogo said "we are solving the memory format server side".

**Pull request merged**
