### PR TITLE
fix: App hang with race condition for tick counter

### LINKED ISSUE #3274: ticksSinceUiUpdate is not thread safe
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.11.0

### Steps to Reproduce

0) Install Xcode 15b8
1) Install Sentry
2) Enable ThreadSanitizer
3) Configure Sentry in code as usual
4) Run app
5) Get stop on `Data race in -[SentryANRTracker detectANRs] `

### Expected Result

Without stop on Data racing

### Actual Result

Stopped on Data racing

Снимок экрана 2023-09-11 в 08 59 15

### Are you willing to submit a PR?

_No response_

### PR DESCRIPTION
**Pull request by brustolin**
## :scroll: Description

Thread sanitizer was complaining about a race condition in the ANR tracker.
Added atomic operations to avoid the race condition

## :bulb: Motivation and Context

closes #3274 

## :green_heart: How did you test it?

Instruments

## :pencil: Checklist

You have to check all boxes before merging:

- [x] I reviewed the submitted code.
- [x]  I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed.
- [x] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

**Comment by armcknight** [comment]
I'm trying to get the thread sanitizer CI job to run.

**Comment by armcknight** [comment]
From slack convo, the thread sanitizer test has been disabled at some point in the past. I think we need to fix that before merging this.

**Comment by armcknight** [comment]
Realized I have such a task already assigned to me. see #3303

**Review by philipphofmann — APPROVED** [review]
LGTM, but the changelog needs fixes. I don't think we need the thread sanitizer job fix merged before merging this. If `SentryANRTrackerTests` are green, we should be good to go. The https://github.com/getsentry/sentry-cocoa/pull/3303 will be a mitigation for future data races. WDYT, @armcknight and @brustolin.

**Comment by armcknight** [comment]
I don't think green ANR tracker tests are enough, they've been green all along. Without changes to them here to somehow ensure the data race is fixed, I don't see how we're validating the fix. I would take an exported Instruments trace here.

**Comment by brustolin** [comment]
>  I don't see how we're validating the fix

In this case I had to validate manually, by running the sample multiple times comparing the outcome. Without a CI is hard to prevent regression, but as far this PR goes, the problem is fixed.

**Pull request merged**
