### PR TITLE
tests: Retry failed tests

### PR DESCRIPTION
**Pull request by kevinrenskers**
Retry failing tests, a max of 3 times in total.

#skip-changelog.

### CODE REVIEW

**Comment by kevinrenskers** [comment]
Found on https://emptytheory.com/2021/11/28/retrying-failed-tests-with-xcode-13-and-continuous-integration/:

> Third party tools such as xcpretty or trainer, which convert xcresult output to JUnit report format may not be set up to parse successful retried tests as test successes. This can result in still seeing the dreaded yellow status in Jenkins even though a retried test eventually succeeded. You may need to trigger your Jenkins pipeline result off of something other than the parsed test result such as the (** TEST SUCCEEDED ** in the output).

Let's see what happens here.

**Comment by brustolin** [comment]
@kevinrenskers can you change anything in the code to trigger the unit tests?

**Comment by kevinrenskers** [comment]
Ah crap that `retry-tests-on-failure` parameter only exists in Xcode 13, so now tests don't run at all on Xcode 12. We could have to make the script even more complex to only use this option for Xcode 13, but then we still have the same problem where tests don't retry on older Xcode versions.

But... why are we even running tests on older Xcode versions? We can run pretty old iOS simulators just on Xcode 13, right?

**Comment by kevinrenskers** [comment]
> but then we still have the same problem where tests don't retry on older Xcode versions

I guess it's better than never retrying at all, at least now we'll have to only manually do it for Xcode 12. Better than nothing. So I made the script a tiny bit more complex, but nothing too crazy.

**Comment by brustolin** [comment]
> why are we even running tests on older Xcode versions? 

Every new test approach has a story behind 😂

**Comment by kevinrenskers** [comment]
Of course in none of these commits I got any failing tests haha

**Review by brustolin — APPROVED** [review]
Lets hope this minimize manual work!!

**Pull request merged**
