### PR TITLE
fix: Add missing entitlement in iOS-Swift sample.

### PR DESCRIPTION
**Pull request by brustolin**
Since we added an App Clip in iOS-Swift sample, we need to update de app entitlement to point to the clip.

_#skip-changelog_

### CODE REVIEW

**Review by philipphofmann — COMMENTED** [review]
I already tried doing that, but this leads to problems with provisioning profiles. I tried to generate new ones, but I had problems with them. I'm not sure if this is still necessary.

**Comment by brustolin** [comment]
> I already tried doing that, but this leads to problems with provisioning profiles. I tried to generate new ones, but I had problems with them. I'm not sure if this is still necessary.

Apple is complaining about the lack of this information, so it must be necessary. 
I will do a little investigation about this profile problem.

**Comment by philipphofmann** [comment]
> Apple is complaining about the lack of this information, so it must be necessary. I will do a little investigation about this profile problem.

I think App Store Connect complained about this in the past when uploading the sample app to TestFlight. Fastlane printed a warning on GitHub Actions. I don't see a warning at the moment, see https://github.com/getsentry/sentry-cocoa/runs/4210028099?check_suite_focus=true

I also got an email in the past with this warning, but don't get one for current uploads.

**Comment by brustolin** [comment]
> I also got an email in the past with this warning, but don't get one for current uploads.

I believe @bruno-garcia, or someone that forward it to him received an email. 
Because he past the email message in discord.

**Comment by philipphofmann** [comment]
Yes, I also got this email @brustolin, but I don't receive it anymore. I'm going to close this.

**Pull request closed without merging**
