### PR TITLE
ref: json serialization error reporting

### PR DESCRIPTION
**Pull request by armcknight**
I had a JSON validation error, but couldn't tell what it was since we simply check for the boolean from `isValidJSON`. I had to implement just attempting the serialization and inspecting the inout error it gives, and learned that at least in my case, serialization also throws exceptions in certain cases, but the exception told me exactly what the problem was. I figured it would be helpful to keep around, but also that we may not want the exception handler in production, so I used some conditional compilation to keep it behaving as it was in release configs, but in all other configs, to get the info from the exception/error.

To that end, added some new functions to construct NSErrors that can include an underlying NSError we may get from a Cocoa library method, or an NSException, with some light refactoring of the implementations in SentryError.

#skip-changelog

Just copying here some details from one of my commits for visibility:

```
before:
    - test if input is valid JSON with `-[NSJSONSerialization
    isValidJSON]` and if not, build our own error.
    - problem: no hints as to why the JSON is invalid

after:
    - attempt direct serialization with `-[NSJSONSerialization
    dataWithJSONObject:options:error:]` and use the library error
    - this can throw an exception in certain failure modes: surround
    the call with try/catch
    - use new functions in SentryError to create an NSError from
    either an NSException or the inout NSError
    - only compile like this for nonrelease builds so we don't incur
    the performance hit of throwing an exception (see apple's docs:
    "For best performance in 64-bit, you should throw exceptions only
    when absolutely necessary.")
```

### CODE REVIEW

**Review by brustolin — APPROVED** [review]
LGTM

**Review by kevinrenskers — APPROVED** [review]

**Comment by armcknight** [comment]
Added some basic tests for the new functions and a test for the serializer with the actual scenario I encountered, trying to add a NSDate directly to a JSON dict for serialization.

**Comment by armcknight** [comment]
No idea why the tests are failing with a compiler error that doesn't make sense and doesn't happen locally; rerunning ⏳

**Comment by armcknight** [comment]
Even if I make the suggested changes locally, then my local build fails. Any idea what could be going on with this @philipphofmann?

**Comment by armcknight** [comment]
@brustolin thanks for pushing that commit, that one builds locally and on CI 👍🏻

**Pull request merged**
