### PR TITLE
ci: Encrypt Match and Appfile of Fastlane

### PR DESCRIPTION
**Pull request by philipphofmann**
## :scroll: Description

We don't want to have the details in the Appfile and Matchfile of Fastlane public.
Therefore we store them encrypted.

## :bulb: Motivation and Context

See description.

## :green_heart: How did you test it?
Running in CI.

## :pencil: Checklist

- [x] I reviewed the submitted code

### CODE REVIEW

**Review by bruno-garcia — CHANGES_REQUESTED** [review]
I'm not sure this is the way go to. It makes it harder to run this locally too if we need to, debug, refactor and improve these things.

Can we use environment variables for the sensitive values instead?

**Comment by philipphofmann** [comment]
@bruno-garcia for debugging locally you just have to run `./fastlane/setup.sh $FASTLANE_ENCRYPTION_KEY`. Otherwise, you have to set a lot environment variables in Github and also locally. It's also nicer to see all the variables in a file instead of them being in a Github secret and you don't know the value.

**Comment by bruno-garcia** [comment]
> @bruno-garcia for debugging locally you just have to run `./fastlane/setup.sh $FASTLANE_ENCRYPTION_KEY`. Otherwise, you have to set a lot environment variables in Github and also locally. It's also nicer to see all the variables in a file instead of them being in a Github secret and you don't know the value.

It's harder without being able to read the contents of the file you're about to run. To read or edit its contents. I'm really not a fan of encrypting these files completely.

If the parameters in them are sensitive, lets use secrets. The script/layout itself shouldn't be encrypted though

**Comment by philipphofmann** [comment]
As discussed, we are going to use Github Secrets instead.

**Pull request closed without merging**
