### PR TITLE
feat: Mark session as crashed

### PR DESCRIPTION
**Pull request by bruno-garcia**
@HazAT @philipphofmann @marandaneto Marking crashed sessions on restart.

Now we have crashed sessions too:

image

### CODE REVIEW

**Comment by philipphofmann** [comment]
I think the problems we have with implementing this feature shows us we should start aligning our SDK with the [Unified API](https://docs.sentry.io/development/sdk-dev/unified-api/) soon. Hacking in too many things is going to slow us down in the long run, as we already discussed yesterday. Taking too much time for doing it properly without the Unified API seems like a waste of time for me, because we need to change it anyway afterward. If you just want to make it work now I'm kind of okay with this hack, but I think in the long run there is no way around the massive refactor you mentioned.

**Comment by HazAT** [comment]
@bruno-garcia 
at 2. Yes, let's just init the client in in `[Hub init]` we have it in other SDKs as well, will send a PR to this PR.

**Comment by HazAT** [comment]
@bruno-garcia @philipphofmann My proposal, a PR to this PR
to fix `2`
https://github.com/getsentry/sentry-cocoa/pull/423

**Comment by bruno-garcia** [comment]
> If you just want to make it work now I'm kind of okay with this hack, but I think in the long run there is no way around the massive refactor you mentioned.

@philipphofmann I'm not planning to merge this PR as-is, it's must a draft to show the issue.
What part of the unfiied API are you referring to? AFAIK the spec doesn't define who instantiates a client (i.e: the caller of Hub ctor or the Hub itself). The PR from Daniel addresses that though.

@HazAT The PR looks good and it solves `2`. Any input on the other items?

**Pull request merged**
