### PR TITLE
accept an autoformat that precommit keeps forcing, preventing commits…

### PR DESCRIPTION
**Pull request by armcknight**
…; unformatted code committed in #2782

#skip-changelog

### CODE REVIEW

**Comment by brustolin** [comment]
Something went wrong. No files to review

**Comment by armcknight** [comment]
The autoformat commit changed it back. Wonder if the runs in pre-commit and the github action are conflicting?

**Comment by philipphofmann** [comment]
> The autoformat commit changed it back. Wonder if the runs in pre-commit and the github action are conflicting?

Sometimes clang format get's an update in CI and then your locale version and the one in CI format the code differently. Maybe `brew upgrade clang-format` helps.

**Comment by armcknight** [comment]
Ah, good call @philipphofmann . I'll close this and revisit if it's a problem after upgrading clang-format locally. It bumped major versions fwiw from 15.x.x to 16.

**Pull request closed without merging**
