### PR TITLE
feat: Collect queue label information for profiles

### PR DESCRIPTION
**Pull request by indragiek**
## :scroll: Description

We previously avoided collecting queue names because the `dispatch_qaddr` field (see diff) would point to a queue that was no longer valid by the time we read the field, causing a crash. I found a note in some Apple code that explains what was happening here: https://github.com/WebKit/WebKit/blob/09225dc168d445890bb0e2a5fa8bc19aef8556f2/Source/WebCore/page/cocoa/ResourceUsageThreadCocoa.mm#L119

The queue had been deallocated by the time we were reading the field. In order to avoid this race condition, in this PR, we suspend the thread before trying to read the field from the queue. Suspending the thread *should* prevent the dispatch queue from deallocated, assuming the deallocation happens on the thread that the queue is currently assigned to. I am not yet 100% confident in this behavior but we will have to try this in production (**for opt-in profiling beta customers only, this doesn't impact anything else**) and see if this works.

This is an example profiling output that contains the queue metadata:
[example_output.txt](https://github.com/getsentry/sentry-cocoa/files/8587061/example_output.txt)

Each sample has a `queue_address` key that can be used to look up the corresponding queue label from the top level `queue_metadata` object.

## :bulb: Motivation and Context

Since most threads on iOS do not have names, having labels for the queues that are running on the threads is crucial for good developer UX in profiling.

## :green_heart: How did you test it?

Added new tests.

## :pencil: Checklist

- [X] I reviewed the submitted code
- [X] I added tests to verify the changes
- [x] I updated the docs if needed
- [ ] Review from the native team if needed
- [X] No breaking changes

### CODE REVIEW

**Review by philipphofmann — COMMENTED** [review]
Hey, @indragiek, 

what a coincidence. I just opened up a PR applying a patch from KSCrash dealing with dispatch queues. Maybe you want to have a look at `sentrycrashthread_getQueueName` https://github.com/getsentry/sentry-cocoa/pull/1790/files

**Comment by indragiek** [comment]
@philipphofmann Took a look and commented on that PR!

If you decide to merge that PR and want me to reuse the implementation, I would not be able to use `sentrycrashthread_getQueueName` as-is since we need to get the queue address rather than the queue name. If you wanted to split that into two functions (one for getting the queue address `dispatch_qaddr`, then another one for getting the queue name from the queue address) then I could use one of them. Otherwise I'm fine duplicating a bit of code here in the interest of simplicity.

**Comment by philipphofmann** [comment]
I removed reading the queue name from https://github.com/getsentry/sentry-cocoa/pull/1790. I'm going to add it in a different PR, and will then split up the function to not have duplicate code.

**Review by philipphofmann — APPROVED** [review]
LGTM 🚀, but maybe worth having maybe @armcknight have a look at the cpp code, as I'm not an expert in it.

**Review by armcknight — APPROVED** [review]
LGTM!

**Pull request merged**
