### PR TITLE
[WIP] feat: NativeScript support

### PR DESCRIPTION
**Pull request by HazAT**
This PR should prepare the SDK to support NativeScript exceptions.
There is a test in place (see json file) and a test case where the conversion of the string should take place.
When I find time for this I will do the changes until then feel free to pick up the work where I left off.

### CODE REVIEW

**Comment by HazAT** [comment]
Hey @bradmartin we are currently releasing all our new SDKs that's why I didn't had time yet to finish this.
I just quickly pulled up this PR if anyone wants to take over, otherwise I will do my best to find time for this as soon as possible.

**Comment by bradmartin** [comment]
@HazAT any chance you can provide some guidance as to what needs to be done here @danielgek I think has mentioned trying to get this to work. I'd also like to take a look in December (things should be slower then 😄).

**Comment by HazAT** [comment]
@bradmartin 
OK, so there is this file called `Tests/Resources/NativeScript.json`
This should emulate a NativeScript crash, but I think only one field may be relevant for you:
https://github.com/getsentry/sentry-cocoa/pull/261/files#diff-6e5cd4e4483facb1c5b996fe69d18574R2186

As far as I understood it, NativeScript writes it's whole stack trace into this message (you proabably have to reverify this).
The task now in this PR is to parse out the stack trace from the string into our `SentryStacktrace` object.

https://github.com/getsentry/sentry-cocoa/pull/261/files#diff-e7fd9ae6dc415bbe17d6f9bf76c75276R365

We already have something similar in our codebase for react-native / cordova
https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryJavaScriptBridgeHelper.m

You can take a look at this class and see how we transform js crashes to frames we can use.

Hope this helps, a bit of learning our code base is involved but the SDK is well tested so it should be doable :)

**Comment by farfromrefug** [comment]
@HazAT I am really interested for a Nativescript integration. I really would like to help on it.
I think it would be fairly easy to implement by "forking" the reacti-native version.

Here are the features that i would love to have:
* support for native exception catching
* support for JS exception catching with source map
* webpack plugin to upload source maps
* gradle plugin for the android version (upload  ProGuard, DexGuard and NDK mapping files)

I think you already have the webpack and gradle plugins right?

Could that become an official support? (added in the graphical interface to setup a project).

I am willing to working on the plugin itself. I did something similar for bugsnag.
I think we could even just improve the nativescript-sentry which already handles the native exceptions.

BTW: {N} recently changed their stack trace formats on iOS and Android to be compliant with source maps support

**Comment by bradmartin** [comment]
@farfromrefug  - this plugin https://github.com/danielgek/nativescript-sentry works fairly well but yea I think we need a little better JS stack trace catching with the source maps. The owner of that plugin is cool and I've done quite a bit to improve it in terms of the support of the android/ios SDKs that Sentry provides.

Just didn't know if you were aware of what that plugin already is doing consuming the native SDKs or not 👍

**Comment by farfromrefug** [comment]
@bradmartin thank I knew about that plugin and I saw how you helped on it. But it does not catch js errors right?
Plus indeed the main point for me is to get source map. I have that working with bugsnag and it is just a live savior. Would love to look a sentry. And it is open sourced ;)

**Comment by bradmartin** [comment]
@farfromrefug  I've enabled this issue as public so you can preview what we have currently logged with sentry capturing the exception on the JS side.

https://sentry.io/share/issue/0f4725e6786e40a2a4fe99b18b69a761/ Having the source map work with it since webpack is now the default on NativeScript apps I think is the last missing piece really. Maybe I'm not thinking of all the other things you're thinking about tho :)

This issue https://sentry.io/share/issue/eaa67d0cf1d04f9ea4d06484a732fa3f/ is a native exception caught. Let me know if you see things that we can try adding to improve the stack and help diagnose the issues tho. Anything to improve is welcome IMO 👍

**Comment by farfromrefug** [comment]
@bradmartin thanks. Though your "native" error is actually a JS error. So you would miss the JS stack right?

**Comment by bradmartin** [comment]
The `raw` of that error is 

```com.tns.NativeScriptException: Calling js method onAnimationEnd failed
Error: No animation target specified.
    at com.tns.Runtime.callJSMethodNative(Runtime.java)
    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
    at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
    at com.tns.Runtime.callJSMethod(Runtime.java:1160)
    at com.tns.Runtime.callJSMethod(Runtime.java:1138)
    at com.tns.Runtime.callJSMethod(Runtime.java:1134)
    at com.tns.gen.android.animation.Animator_AnimatorListener.onAnimationEnd(Animator_AnimatorListener.java:50)
    at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:73)
    at com.airbnb.lottie.utils.LottieValueAnimator.doFrame(LottieValueAnimator.java:101)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090)
    at android.view.Choreographer.doCallbacks(Choreographer.java:893)
    at android.view.Choreographer.doFrame(Choreographer.java:809)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
    at android.os.Handler.handleCallback(Handler.java:907)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7625)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)```

which I'm not calling directly when it throws. Not ideal without more context of course.

I think getting the JS stack and native stack is kinda the last missing piece IMO for the NS +Sentry integration to be feature rich.

**Comment by farfromrefug** [comment]
@bradmartin Yes the context is not really good enough.
With bugnsag this is what i get:
Screen Shot 2019-11-04 at 16 46 16

Now it s good to mention that bugnsag have great gradle/cocoapods plugins which auto publish dsym and object dumps. And they are open source! 
https://github.com/bugsnag/cocoapods-bugsnag
https://github.com/bugsnag/bugsnag-android-gradle-plugin

**Pull request closed without merging**
