### PR TITLE
Fix: SDK detects OutOfMemory after device reboot

### PR DESCRIPTION
**Pull request by sepbehroozi**
## :scroll: Description

If the host app has been terminated due to device reboot, SentrySDK assumes it as a WatchdogTermination crash. In such cases, mostly, the boot time will be mentioned as "a few seconds before this event". 

Screenshot 2023-10-19 at 09 52 27

The idea behind this fix is that if the system boot time has been changed since the previous app launch, most likely the app has been terminated due to the reboot and the SentrySDK should not consider it as a WatchdogTermination crash.

## :bulb: Motivation and Context

This change helps reducing the amount of false WatchdogTermination events detected by the SDK.

## :green_heart: How did you test it?

There's a new test case added in the `SentryWatchdogTerminationsTrackerTests.swift` file, which sets the previous app-launch time to different value and expects not sending any OOM event.

## :pencil: Checklist

You have to check all boxes before merging:

- [x] I reviewed the submitted code.
- [x] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

**Comment by sepbehroozi** [comment]
> Thanks @sepbehroozi for contributing. I believe this change makes sense.
> Would you mind taking a look at the tests that are failing?

Hello @brustolin 
Thanks for checking the PR.
Of course. I'll check them later today 👍

**Comment by sepbehroozi** [comment]
> Thanks @sepbehroozi for contributing. I believe this change makes sense. Would you mind taking a look at the tests that are failing?

Hey @brustolin. I believe the reason for the failed tests was that the `Fixture` class of the `SentryCrashIntegrationTests` doesn't introduce a mock `SysctlWrapper` (In this case, the `TestSysctl()`) to the `SentryDependencyContainer`. That's why the `buildCurrentAppState` function in the `SentryAppStateManager` class uses the real `SentrySysctl` class when getting called from the `SentryCrashIntegrationTests` tests.
What I thought would be a good solution in this case, setting the `sysctlWrapper` of `SentryDependencyContainer.sharedInstance()` to `TestSysctl()` in the Fixture's initializer. I hope I could make sense of it :))

**Review by philipphofmann — COMMENTED** [review]
Good catch, thanks, @sepbehroozi 🥳.  I also think this change makes sense. I leave it up to @brustolin to give you a final review.

**Review by brustolin — APPROVED** [review]
LGTM

**Pull request merged**
