### PR TITLE
ref: move SentryCrash singleton to SentryDependencyContainer

### PR DESCRIPTION
**Pull request by armcknight**
Same deal, move the singleton to SentryDependencyContainer.

After making this change, SentryCrashInstallationTests.testUninstall fails when running the full test suite locally, but not when run by itself. Seems like there's a bug in the tests. Haven't sussed it out yet though.

#skip-changelog

### CODE REVIEW

**Comment by brustolin** [comment]
Please fix CI.

**Comment by brustolin** [comment]
We need CI fixed.

**Review by brustolin — APPROVED** [review]
LGTM.

Just make sure CI is working properly before merging this.

**Comment by armcknight** [comment]
Still not sure why the test is failing for tvOS to test uninstalling the crash handler. But, I was unable to even run it locally, which #3382 should fix. It could be related to dirty state between tests, which #3381 attempts to fix more.

**Review by philipphofmann — APPROVED** [review]
Thanks @armcknight 👍

**Comment by armcknight** [comment]
Found it: SentryCrashInstallationReporterTests never uninstalled the crash reporters it installed.

**Pull request merged**
