### PR TITLE
test: Run Objective-C sample in iOS 12

### PR DESCRIPTION
**Pull request by brustolin**
Run Objective-C sample in iOS 12.

#skip-changelog

### CODE REVIEW

**Comment by bruno-garcia** [comment]
Cool stuff!
I think it's good that we target a lower version here to make sure things work since we technically support iOS 9+

**Comment by bruno-garcia** [comment]
@brustolin is this still a draft PR?

If it's ready for review, @philipphofmann is back on Monday so we could consider merging

**Comment by philipphofmann** [comment]
Thanks, @brustolin for doing this. Can you maybe make this ready for review?

**Review by bruno-garcia — APPROVED** [review]
LGTM!

We can keep the Swift one pointing to a later version, and the Obj-C to an older one.

**Review by philipphofmann — APPROVED** [review]
LGTM. This is nice 👏
Screen Shot 2021-05-04 at 08 38 23

**Pull request merged**
