### PR TITLE
feat: Include app permissions for app extensions

### LINKED ISSUE #2026: Investigate app permission checks from extensions
### Description

In #1984 we added app permissions to the event payload, but we only do this when running in the main app. Let's investigate if we can remove that limitation and also run this in extensions. Need to make sure it won't cause crashes.

### PR DESCRIPTION
**Pull request by kevinrenskers**
## :scroll: Description

Simply remove the check that prevent the permission observer from running in an app extension.

#skip-changelog (part of #1984 which is in the changelog for the upcoming version)

## :bulb: Motivation and Context

Closes #2026.

## :green_heart: How did you test it?

I created an app with app extensions (IntentUI and Widget) and ran all the exact same code to fetch app permissions, without any problems. In https://github.com/getsentry/sentry-cocoa/pull/1984 it was suggested this could lead to crashes but I am not seeing any proof of that.

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

**Review by philipphofmann — APPROVED** [review]
LGTM 🚀

**Comment by philipphofmann** [comment]
Please also add a changelog entry, @kevinrenskers.

**Comment by kevinrenskers** [comment]
> Please also add a changelog entry, @kevinrenskers.

Ah, I assumed it would be part of what is now 7.24.0-beta.0, so it would be part of the same changelog. Added one now!

**Comment by choulepoka** [comment]
I do not know why, but this changes seems to trigger an `Invalid Binary` when submitting to the app store for permission `NSAppleMusicUsageDescription`.

Quick-Fix is to revert to v7.23.0

**Comment by kevinrenskers** [comment]
Also, this isn't part of 7.24.0.

**Comment by choulepoka** [comment]
Here is the message from Apple:

```
Dear Developer,

We identified one or more issues with a recent delivery for your app, "Connect.Staging" 9022.9.2 (3341). Please correct the following issues, then upload again.

ITMS-90683: Missing Purpose String in Info.plist - Your app‘s code references one or more APIs that access sensitive user data. The app‘s Info.plist file should contain a NSAppleMusicUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources
```

Our app is not using the Media Library or any related frameworks. 

I think the culprit is `MPMediaLibrary.authorizationStatus` in the sentry code.

**Pull request merged**
