### PR TITLE
test: iOS 9 Swift sample

### LINKED ISSUE #1345: Sample Apps Support SDKs Min Versions
Our current sample apps target a high min SDK version. We should change them or add new sample apps to run UI tests on these OS versions.

### PR DESCRIPTION
**Pull request by brustolin**
Sentry SDK targets iOS 9 and we have an objc sample targeting iOS 9. The Swift sample targets iOS 13, but it uses UIScenes, to lower the SDK target we need to remove UIScenes.

UIScene is something we swizzle, so a new sample was created just to test a proper app launch using UIScene.

Closes #1345 

_#skip-changelog_

### CODE REVIEW

**Comment by philipphofmann** [comment]
Just make sure to run a web request on an iOS 10 simulator. Then we are good to merge this.

**Comment by philipphofmann** [comment]
Please also add simple UI tests that launch the app and fire off one web request. We should run this UI test in SauceLabs on an iOS 10 device.

**Comment by philipphofmann** [comment]
Can we please make the iOS10-Swift the main target, call it iOS-Swift, and rename the existing iOSSwift to iOSSwift-UIScenes or something.

**Comment by brustolin** [comment]
> Can we please make the iOS10-Swift the main target, call it iOS-Swift, and rename the existing iOSSwift to iOSSwift-UIScenes or something.

The main sample remains iOS-Swift targeting iOS 9.0, and the new sample is called iOS13-Swift.

**Review by philipphofmann — APPROVED** [review]
Awesome thanks 🙏

**Pull request merged**
