### PR TITLE
fix: Redundant x29 GP register on arm64 and UBSan crash

### LINKED ISSUE #963: iOS/arm64 CPU frame pointer duplicated as GP x29, Sentry SDK crashes in Undefined Behavior Sanitizer
### Environment

How do you use Sentry? Sentry SaaS (sentry.io)

Which SDK and version? sentry-cocoa 6.2.0

### Steps to Reproduce

Capture any exception on iOS/arm64

### Expected Result

Exception along with CPU registers as 28 GP registers + FP & LR would be visible in Sentry afterwards.

### Actual Result

The Sentry SDK invents a register (x29) and crashes in UBSan.

UBSan message:

```
/redacted/DerivedData/redacted/SourcePackages/checkouts/sentry-cocoa/Sources/SentryCrash/Recording/Tools/SentryCrashCPU_arm64.c:120:16: runtime error: index 29 out of bounds for type '__uint64_t const[29]'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /redacted/DerivedData/redacted/SourcePackages/checkouts/sentry-cocoa/Sources/SentryCrash/Recording/Tools/SentryCrashCPU_arm64.c:120:16
```

### Cause

I had a brief look at the sources. Turns out the Sentry SDK simply defines GP registers x0-x29 _and_ FP. However, FP and x29 is the same register. Here is the struct from mach/arm as reference:

```
_STRUCT_ARM_THREAD_STATE64
{
	__uint64_t __x[29]; /* General purpose registers x0-x28 */
	__uint64_t __fp;    /* Frame pointer x29 */
	__uint64_t __lr;    /* Link register x30 */
	__uint64_t __sp;    /* Stack pointer x31 */
	__uint64_t __pc;    /* Program counter */
	__uint32_t __cpsr;  /* Current program status register */
	__uint32_t __pad;   /* Same size for 32-bit or 64-bit clients */
};
```

And here is what the Sentry SDK does with it:

```
uint64_t
sentrycrashcpu_registerValue(const SentryCrashMachineContext *const context, const int regNumber)
{
    if (regNumber <= 29) {
        return context->machineContext.__ss.__x[regNumber];
    }

    switch (regNumber) {
    case 30:
        return context->machineContext.__ss.__fp;
...
```

As you can see `sentrycrashcpu_registerValue(29)` and `sentrycrashcpu_registerValue(30)` are bound to return the same value. Here is a screenshot with the error visible in Sentry's UI that demonstrates the issue:

Screenshot 2021-02-25 at 21 30 17

### PR DESCRIPTION
**Pull request by mologie**
## :scroll: Description

UBSan detected an out-of-bounds read from machineContext.__ss.__x. The register that was previously shown as x29 in Sentry is in fact just the FP register. This commit removes the duplicate (and thus the out-of-bounds read that triggered UBSan).

## :bulb: Motivation and Context

Fixes #963

## :green_heart: How did you test it?

Ran it against my local Sentry instance, the stray register disappears and UBSan no longer reports errors:

Screenshot 2021-02-25 at 22 12 51

## :pencil: Checklist

- [x] I reviewed the submitted code
- [ ] I added tests to verify the changes
- [ ] I updated the CHANGELOG if needed
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

**Review by philipphofmann — COMMENTED** [review]
Thanks, @mologie, for opening up this PR. The change makes sense to me. Still, I want a second pair of eyes from someone from our native team.

**Review by Swatinem — COMMENTED** [review]
so if I found the correct definition, this comes from here:

https://github.com/apple-opensource/xnu/blob/88d1494beeb1819aadc81f2d1926dc5979dd261b/osfmk/mach/arm/_structs.h#L155-L161

Although that file has tons of defines for this, gated on some obscure ifdefs.

Anyhow, I think this is correct, and I wonder how this ever used to work before?

**Review by Swatinem — APPROVED** [review]

**Review by jan-auer — APPROVED** [review]

**Comment by philipphofmann** [comment]
Thanks, @mologie, for this PR. The next time please also add an entry to the changelog. I'm going to do that for you now because I want to publish a bugfix right now.

**Comment by mologie** [comment]
@Swatinem 
> Anyhow, I think this is correct, and I wonder how this ever used to work before?

A good bit of exception handling disables itself in debug mode unless you hotwire it. This probably made it invisible to UBSan and unnoticed so far. Other than that the impact was minor: It simply invented a new register that had the value of FP (because it was the field after the array and thus target of the out-of-bounds read).

Thanks for the quick review and merge to both of you. Cheers!

**Comment by Swatinem** [comment]
> it was the field after the array and thus target of the out-of-bounds read

Yes ofc, that makes sense!

**Pull request merged**
