### PR TITLE
fix: privacy manifest collection purposes type

### PR DESCRIPTION
**Pull request by FelixHerrmann**
## :scroll: Description

Change NSPrivacyCollectedDataTypePurposes type from string to array.

**Note:** Using the Property List representation of Xcode will use tabs instead of spaces under the hood, that's why the git diff is not super readable...

## :bulb: Motivation and Context

We have started configuring the privacy manifest for our app. The generated Privacy Report from the Xcode Organizer presented us the following error:
Screenshot 2023-09-11 at 18 11 07

Checking Sentry's manifest file confirmed it, the NSPrivacyCollectedDataTypePurposes (Collection Purposes) had the wrong type, string instead of array.

## :green_heart: How did you test it?

I haven't tested it by generating another report but [Apple's docs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests#4144131) clearly define it as an array of strings and the Xcode Property List representation shows the correction display names instead of the underlying key (Item 1 is fixed, Item 2 is original):
Screenshot 2023-09-11 at 17 55 44

## :pencil: Checklist

You have to check all boxes before merging:

- [x] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

**Comment by armcknight** [comment]
Thanks @FelixHerrmann for the fix! I pushed a changelog fix and let's see how CI does on that commit.

For easier diffing, here're the significant changes not including whitespace: 
image

**Comment by FelixHerrmann** [comment]
> For easier diffing, here're the significant changes not including whitespace:

Yes, much better to read, thanks for sending this!

**Comment by armcknight** [comment]
I'm going to close this one in favor of #3276, I think there's a permission error with the CI jobs on this one. Thanks again for the PR!

**Comment by FelixHerrmann** [comment]
All good, thanks for picking this up so quickly!

**Comment by FelixHerrmann** [comment]
> I think there's a permission error with the CI jobs on this one.

@armcknight do you think thats a general issue or just with this particular PR? I have another small fix for you but I can also open an issue, let me know!

**Comment by armcknight** [comment]
I think it's because it's in a fork. If you push a branch directly to this remote for a PR, we should be able to authorize CI jobs containing sensitive info. Thanks for all your efforts @FelixHerrmann 🙏🏻

**Comment by FelixHerrmann** [comment]
Gotcha, will try next time! I just saw that the issue already got fixed in #3270, it's just not released yet 👍🏻

**Pull request closed without merging**
