### PR TITLE
fix: Move header reference out of `extern C`

### PR DESCRIPTION
**Pull request by brustolin**
## :scroll: Description

Removing header references from `extern C` because they are causing compile errors with Android Studio and flutter.

## :bulb: Motivation and Context

close https://github.com/getsentry/sentry-dart/issues/1781

## :pencil: Checklist

You have to check all boxes before merging:

- [x] I reviewed the submitted code.
- [x] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed.
- [x] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

**Review by philipphofmann — COMMENTED** [review]
Can we add something in CI that prevents that mistake in the future? What else is missing so we can merge this @brustolin?

**Comment by brustolin** [comment]
> Can we add something in CI that prevents that mistake in the future? What else is missing so we can merge this @brustolin?

This is kind of a shot in the dark. Everything I read about it says it's okay (or we should) to move the includes out of extern C. CI is not complaining about it, and other tests where I forced the file to use a C++ compiler were okay. But I could not reproduce the error before the changes.

I'm waiting for the user to test this branch; I sent them instructions in the original issue.

**Comment by kahest** [comment]
The user in https://github.com/getsentry/sentry-dart/issues/1781#issuecomment-1882507062 reported that this fixed their issue

**Review by philipphofmann — APPROVED** [review]
LGTM

**Pull request merged**
