### PR TITLE
feat: Allow nil in setExtraValue on SentryScope to remove key

### PR DESCRIPTION
**Pull request by lhunath**
## :scroll: Description

This enables compatibility with the API used by NSMutableDictionary, on
which this API appears to be modeled and which this implementation is
using under the hood.

## :bulb: Motivation and Context

https://github.com/getsentry/sentry-cocoa/issues/701#issuecomment-686689194

## :green_heart: How did you test it?

`Tests/SentryTests/SentryScopeTests.m`'s `testRemoveExtra` updated.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify the changes
- [ ] I've updated the CHANGELOG
- [x] No breaking changes

### CODE REVIEW

**Review by bruno-garcia — APPROVED** [review]
Nice! thanks

**Comment by bruno-garcia** [comment]
There's a broken test and lint in CI. Maybe unrelated to your change

**Review by philipphofmann — APPROVED** [review]
Thanks @lhunath 👏 .

**Comment by philipphofmann** [comment]
@lhunath, Travis is telling us that we have some code formatting issues in here. You can fix them by calling `make format`. Please push the changes and then we are good to merge this.

**Pull request merged**
