### PR TITLE
fix: Change SentryScope setTagValue to NSString

### PR DESCRIPTION
**Pull request by philipphofmann**
## :scroll: Description

The type for value in SentryScope.setTagValue was id. Tags are key/values
of strings. Now the value is changed to NSString.

## :bulb: Motivation and Context

Fixes GH-519

## :green_heart: How did you test it?
Added a unit test.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify the changes
- [x] All tests are passing
- [x] I've updated the CHANGELOG

## :crystal_ball: Next steps
None.

### CODE REVIEW

**Comment by ainopara** [comment]
Hi, should we also add _Nullable annotation to value of type like what I did in my fork
https://github.com/ainopara/sentry-cocoa/commit/e574155b698fbbbf8dce83389dd639f0beb7a953

**Comment by philipphofmann** [comment]
Thanks, @ainopara for pointing this out. If your use case is to remove a tag we can easily do that by adding a method `removeTag` like we already have it on [Android](https://github.com/getsentry/sentry-android/blob/2798e65a6f9c5a15eecff6f79e4a59e60b083f87/sentry-core/src/main/java/io/sentry/core/Scope.java#L248). I would not add `__Nullable`.

**Comment by philipphofmann** [comment]
> We need to bump a major version for this, if we're doing semver that is

We could also mark the existing `- (void)setTagValue:(id)value forKey:(NSString *)key` as deprecated and add a new function `- (void)setTag:(id)value forKey:(NSString *)key` to avoid a major bump here. The downside is that it doesn't follow the naming scheme of `setExtraValue` and `setContextValue`. Can you add anything to that @bruno-garcia ?

**Comment by philipphofmann** [comment]
@ainopara I opened up a PR for adding `removeTag` #529 .

**Comment by ainopara** [comment]
> @ainopara I opened up a PR for adding `removeTag` #529 .

👍Add method to remove tag is good enough for me. Thank you for you quick fix.

**Comment by philipphofmann** [comment]
> > @ainopara I opened up a PR for adding `removeTag` #529 .
> 
> 👍Add method to remove tag is good enough for me. Thank you for your quick fix.

Thanks for letting us now. 👍

**Pull request merged**
