### PR TITLE
ref: create root object as superclass for all SDK classes

### PR DESCRIPTION
**Pull request by armcknight**
In service of app launch profiling, create a root object for all other classes to descend from as subclasses. This is to ensure we have an earliest possible moment to automatically run code, in the root class' `+[load]` method, as if we left it some other class load method, there is no guarantee when it would be called. The header for the method that calls the load methods states: 
```
* call_load_methods
* Call all pending class and category +load methods.
* Class +load methods are called superclass-first. 
* Category +load methods are not called until after the parent class's +load.
```
(from https://opensource.apple.com/source/objc4/objc4-787.1/runtime/objc-loadmethod.mm.auto.html)

Forcing this order to always start the profiler in the very first class load provides two benefits:
1. it always runs as early as possible. in my tests, i observed around 10ms to load all the sentry classes, enough for definitely 1, and sometimes 2 profiler samples (for context, we need a minimum of 2 samples to be able to show any data on a flamechart)
2. it enforces consistent results, in case we want to aggregate across launches

here is a sample result of the class loads, with nanosecond timestamps; the total time to load all the classes in this run took only 2 ms, but i've observed it taking up to 11 ms in the past.
<details>
19942295419000 +[SentryBaseObject load]
19942295523875 +[SentryMessage load]
19942295526416 +[SentryCrashScopeObserver load]
19942295527875 +[SentryAppStartMeasurement load]
19942295564458 +[SentryBaseIntegration load]
19942295566583 +[SentryAutoBreadcrumbTrackingIntegration load]
19942295592750 +[SentryScreenFrames load]
19942295594458 +[SentryEnvelopeRateLimit load]
19942295595958 +[SentryClientReport load]
19942295597250 +[SentryQueueableRequestManager load]
19942295622291 +[SentryAppStartTracker load]
19942295862500 +[SentryDispatchQueueWrapper load]
19942295870500 +[SentryFramesTracker load]
19942295872208 +[SentrySwiftAsyncIntegration load]
19942295873708 +[SentryDsn load]
19942295875041 +[SentryDebugMeta load]
19942295876708 +[SentryWatchdogTerminationTracker load]
19942295878333 +[SentryNetworkTrackingIntegration load]
19942295879625 +[SentryClient load]
19942295907708 +[SentryCrashDefaultMachineContextWrapper load]
19942295914291 +[SentryNSError load]
19942295958458 +[SentryNSDataTracker load]
19942295982958 +[SentryRateLimitParser load]
19942295985458 +[SentryTracerConfiguration load]
19942296010750 +[SentrySpanContext load]
19942296012375 +[SentryTransactionContext load]
19942296013708 +[SentryHttpStatusCodeRange load]
19942296042250 +[SentryMXExceptionParams load]
19942296043750 +[SentryMetricKitIntegration load]
19942296045125 +[SentryUIEventTrackingIntegration load]
19942296046458 +[SentrySerialization load]
19942296071375 +[SentryCrashWrapper load]
19942296074416 +[SentryFileIOTrackingIntegration load]
19942296099791 +[SentryThreadInspector load]
19942296102875 +[SentryTransportAdapter load]
19942296131583 +[SentrySdkInfo load]
19942296155708 +[SentryDispatchFactory load]
19942296159000 +[SentryAutoSessionTrackingIntegration load]
19942296160458 +[SentryUIEventTracker load]
19942296161750 +[SentrySubClassFinder load]
19942296163083 +[SentryANRTracker load]
19942296187416 +[SentryOptions load]
19942296216083 +[SentryEnvelopeItemHeader load]
19942296217708 +[SentryEnvelopeAttachmentHeader load]
19942296219041 +[SentryByteCountFormatter load]
19942296248250 +[SentryAppStartTrackingIntegration load]
19942296251250 +[SentrySamplingContext load]
19942296252625 +[SentryWatchdogTerminationLogic load]
19942296253958 +[SentryInAppLogic load]
19942296255291 +[SentryCrashReportFilterPassthrough load]
19942296256583 +[SentryCrashReportFilterCombine load]
19942296257916 +[SentryCrashReportFilterPipeline load]
19942296282083 +[SentryCrashReportFilterObjectForKey load]
19942296284291 +[SentryCrashReportFilterConcatenate load]
19942296285708 +[SentryCrashReportFilterSubset load]
19942296287000 +[SentryCrashReportFilterDataToString load]
19942296288333 +[SentryCrashReportFilterStringToData load]
19942296289625 +[SentryCrashDoctorParam load]
19942296290916 +[SentryCrashDoctorFunctionCall load]
19942296292208 +[SentryCrashDoctor load]
19942296293541 +[SentryNSNotificationCenterWrapper load]
19942296294875 +[SentryFrame load]
19942296319916 +[SentryBinaryImageInfo load]
19942296321541 +[SentryBinaryImageCache load]
19942296322916 +[SentryNetworkTracker load]
19942296346958 +[SentryInstallation load]
19942296350291 +[SentryAppState load]
19942296351750 +[SentryNSURLSessionTaskSearch load]
19942296353041 +[SentryDisplayLinkWrapper load]
19942296354375 +[SentrySystemWrapper load]
19942296355666 +[SentryNSURLRequest load]
19942296383791 +[SentryNSURLRequestBuilder load]
19942296387000 +[SentryException load]
19942296388333 +[SentryExtraContextProvider load]
19942296389708 +[SentryDebugImageProvider load]
19942296420625 +[SentryScreenshot load]
19942296422250 +[SentryHub load]
19942296483458 +[SentryPropagationContext load]
19942296511833 +[SentrySpan load]
19942296515375 +[SentryNoOpSpan load]
19942296516916 +[SentryPredicateDescriptor load]
19942296543125 +[SentrySystemEventBreadcrumbs load]
19942296545291 +[SentryMeta load]
19942296571958 +[SentryViewHierarchyIntegration load]
19942296573500 +[SentryUIDeviceWrapper load]
19942296574791 +[SentryHttpDateParser load]
19942296576083 +[SentryTracer load]
19942296598625 +[SentryEnvelopeHeader load]
19942296600750 +[SentryEnvelopeItem load]
19942296602041 +[SentryEnvelope load]
19942296628625 +[SentryBreadcrumb load]
19942296632541 +[SentryConcurrentRateLimitsDictionary load]
19942296633958 +[SentryEvent load]
19942296660125 +[SentryTransaction load]
19942296661583 +[SentryWatchdogTerminationScopeObserver load]
19942296662958 +[SentryMechanismMeta load]
19942296665666 +[SentryTraceHeader load]
19942296666916 +[SentryHttpTransport load]
19942296698083 +[SentryReachability load]
19942296720708 +[SentryFrameRemover load]
19942296722250 +[SentrySwizzleWrapper load]
19942296723500 +[SentryFramesTrackingIntegration load]
19942296724875 +[SentryAppStateManager load]
19942296726166 +[SentryThreadWrapper load]
19942296727458 +[SentryId load]
19942296728750 +[SentryNSDataSwizzling load]
19942296753125 +[SentryAsynchronousOperation load]
19942296809416 +[SentryRequestOperation load]
19942296810958 +[SentryLog load]
19942296812250 +[SentryCrashReportConverter load]
19942296833208 +[SentryRequest load]
19942296834708 +[SentryMigrateSessionInit load]
19942296836250 +[SentrySession load]
19942296837500 +[SentryNSTimerFactory load]
19942296860625 +[SentryDiscardedEvent load]
19942296880875 +[SentryANRTrackingIntegration load]
19942296883500 +[SentryTimeToDisplayTracker load]
19942296884875 +[SentrySessionTracker load]
19942296905208 +[SentryMechanism load]
19942296906583 +[SentryStacktrace load]
19942296907916 +[SentryDefaultObjCRuntimeWrapper load]
19942296909291 +[SentryCrashCString load]
19942296910583 +[SentryBreadcrumbTracker load]
19942296934291 +[SentryCrashIntegration load]
19942296954250 +[SentryProfiler load]
19942296956875 +[SentryCrash load]
19942296977666 +[SentryCrashInstallation load]
19942296998208 +[SentryCrashInstallationReporter load]
19942296999833 +[SentryScreenshotIntegration load]
19942297001125 +[SentryTransportFactory load]
19942297002458 +[SentryNSProcessInfoWrapper load]
19942297003708 +[SentryUserFeedback load]
19942297005000 +[SentrySDK load]
19942297026208 +[SentryScope load]
19942297046166 +[SentrySample load]
19942297047708 +[SentryDispatchSourceWrapper load]
19942297049000 +[SentryUIEventTrackerTransactionMode load]
19942297069833 +[SentryCrashJSONCodec load]
19942297071500 +[SentryDefaultRateLimits load]
19942297072791 +[SentryDateUtil load]
19942297074041 +[SentryThread load]
19942297094083 +[SentryTracesSamplerDecision load]
19942297096583 +[SentryTracesSampler load]
19942297097875 +[SentryMetricReading load]
19942297099208 +[SentryMetricProfiler load]
19942297119375 +[SentryCrashDefaultBinaryImageProvider load]
19942297121000 +[SentryRandom load]
19942297122250 +[SentryFileContents load]
19942297143875 +[SentryViewHierarchy load]
19942297146458 +[SentryUIViewControllerSwizzling load]
19942297166625 +[SentryWatchdogTerminationTrackingIntegration load]
19942297169208 +[SentryPerformanceTrackingIntegration load]
19942297170708 +[SentrySessionCrashedHandler load]
19942297172000 +[SentryGeo load]
19942297191833 +[SentryDependencyContainer load]
19942297193500 +[SentryLogOutput load]
19942297194750 +[SentryUser load]
19942297214166 +[SentryGlobalEventProcessor load]
19942297215583 +[SentryRetryAfterHeaderParser load]
19942297216916 +[SentryCrashStackEntryMapper load]
19942297218458 +[sentrycrashobjc_NSError_SimpleConstructor_AOG8G load]
19942297219833 +[SentrySpanId load]
19942297221083 +[SentryCrashReportSink load]
19942297241541 +[SentryUIViewControllerPerformanceTracker load]
19942297243083 +[SentryTraceContext load]
19942297264291 +[SentryPerformanceTracker load]
19942297266416 +[SentryMeasurementValue load]
19942297267708 +[SentryCoreDataTrackingIntegration load]
19942297269083 +[SentrySysctl load]
19942297275291 +[SentryProfilerMutableState load]
19942297295958 +[SentryProfilerState load]
19942297298125 +[SentryCoreDataSwizzling load]
19942297299458 +[SentrySwizzleInfo load]
19942297300708 +[SentrySwizzle load]
19942297301958 +[SentryStacktraceBuilder load]
19942297327250 +[SentryBaggage load]
19942297354541 +[SentryCurrentDateProvider load]
19942297357333 +[SentryUIApplication load]
19942297358625 +[SentryAttachment load]
19942297359875 +[SentryFileManager load]
19942297381458 +[SentryProfilesSamplerDecision load]
19942297383875 +[SentryProfilesSampler load]
19942297385250 +[sentrycrashobjc_DeepSearchP5EM1B9 load]
19942297387750 +[SentryMeasurementUnit load]
19942297389375 +[SentryMeasurementUnitDuration load]
19942297391291 +[SentryMeasurementUnitInformation load]
19942297392666 +[SentryMeasurementUnitFraction load]
19942297393916 +[SentryCrashInstReportField load]
19942297395458 +[SentryCrashExceptionApplication load]
19942297417875 +[SentryCoreDataTracker load]
19942297421416 +[NSLocale(Sentry) load]
19942297422875 +[NSMutableDictionary(Sentry) load]
19942297424166 +[UIViewController(Sentry) load]
19942297426333 +[NSData(Sentry) load]
19942297427916 +[NSDictionary(SentrySanitize) load]
19942297429208 +[NSDate(SentryExtras) load]
19942297431041 +[NSData(SentryCompression) load]
19942297432291 +[NSError(SentrySimpleConstructor) load]
19942297433708 +[NSArray(SentrySanitize) load]
19942297435833 +[NSDictionary(DeepSearch) load]
19942297437541 +[NSArray(DeepSearch) load]
</details>

This PR also contains some minor tweaks to some forward class declarations and imports.

### CODE REVIEW

**Comment by brustolin** [comment]
IMO 1 or 2 profile samples is not a good reason for this hack solution.
This also wont play well with Swift code that will be used more and more.

**Comment by philipphofmann** [comment]
@armcknight, thanks for the investigation of the superclass approach 👏 .

If this only ensures that we start the profiler earlier in our Sentry code, I wonder if it's worth it. Users will mainly be interested in the Sentry profiler starting earlier than other libraries. I think we should do some tests for apps with multiple libraries and see if that approach helps Sentry's classes get loaded before other libraries. If it does, then maybe it's worth it. The early running profiler would capture long-running methods in +load methods of other libraries, so that would be a great insight.

Another approach is to exclude this feature in the first iteration and see how it goes. We can also look at customer data and check if we must start the profiler earlier.

**Comment by brustolin** [comment]
What If we add this base class only to the classes that implement `+[load]`?

**Comment by armcknight** [comment]
Thanks for the discussion @philipphofmann and @brustolin, here are some responses:

> IMO 1 or 2 profile samples is not a good reason for this hack solution.

True, that is a marginal result in and of itself, but it also gives as much time as possible to do the profiler initialization to capture as much meaningful info as possible for whatever happens afterwards.

> What If we add this base class only to the classes that implement +[load]?

load is always called on a nsobject subclass, regardless of whether it implements an _override_.

> This also wont play well with Swift code that will be used more and more.

Could you elaborate on this? Are you talking about swift structs/enums and classes that don't descend from nsobject? those all have runtime entrypoints after the objc class load process. i don't think there's a way to execute code from them any earlier than the objc class load calls. For instance, static and global variables in swift definitions are only assigned on first use, not at some point in the runtime initialization. the only point of this change is to be able to automatically run code as early as possible, so swift code shouldn't have to care about the class hierarchy.

> If this only ensures that we start the profiler earlier in our Sentry code, I wonder if it's worth it. Users will mainly be interested in the Sentry profiler starting earlier than other libraries. 

Yep, I agree. One thing I planned to document is to suggest that to get the best results out of app launch profiling, they need to statically link Sentry and then take a similar approach to what I did here in their own classes, and call an API to start our profiler (something like `SentrySDK.startAppLaunchProfile` that we'll expose).

> I think we should do some tests for apps with multiple libraries and see if that approach helps Sentry's classes get loaded before other libraries. 

This is why I'd recommend statically linking Sentry and employing this superclass strategy, I don't think there's any guarantee about the order that frameworks are loaded in.

> Another approach is to exclude this feature in the first iteration and see how it goes. We can also look at customer data and check if we must start the profiler earlier.

I'd be good with that, I'll close this for now.

**Comment by philipphofmann** [comment]
Thanks, @armcknight, for the clarification 👍 . I agree with your points and closing the PR for now.

This PR will help us to understand why we voted against this approach. Do you think it makes sense to add a reference to this PR to https://github.com/getsentry/sentry-cocoa/blob/main/develop-docs/DECISIONS.md with a short entry, so we'll be able to find it later, or do you think this PR is enough? Both approaches work for me.

**Comment by armcknight** [comment]
@philipphofmann I made a note of it in the description of #3529, I think that will be sufficient for now. Thanks for following up!

**Pull request closed without merging**
