### PR TITLE
ci: Pin Fastlane to 2.210.1

### PR DESCRIPTION
**Pull request by philipphofmann**
Pin fastlane to 2.210.1 to avoid CI failure with "Could not install WWDR certificate" until https://github.com/fastlane/fastlane/issues/20960 is resolved.

#skip-changelog

### CODE REVIEW

**Review by armcknight — COMMENTED** [review]
Let's add `Gemfile` to the `pull_request.paths` trigger list in `.github/workflows/build.yml` so it can run for this and future changes to the Gemfile.

ETA: you might be gone for the day, hope you don't mind if I do this for you!

**Comment by philipphofmann** [comment]
> ETA: you might be gone for the day, hope you don't mind if I do this for you!

**Review by armcknight — APPROVED** [review]
Looks like it works, this job was one of the ones failing (like this build https://github.com/getsentry/sentry-cocoa/actions/runs/3963387150/jobs/6791153726#step:4:113) and now it's passing: https://github.com/getsentry/sentry-cocoa/actions/runs/3959723694/jobs/6782921621

**Comment by joshdholtz** [comment]
Hey! Sorry about this issue. Will get a fix out for _fastlane_ so you don't have to pin it!

**Comment by philipphofmann** [comment]
Thanks for the update, @joshdholtz. No worries, the workaround was easy and it's easy to remove.

**Pull request merged**
