### PR TITLE
TEST: Mergeable Sample

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

I have added the mergeable flags to our build script and tested release builds in the Simulator on macOS.

The sample project is embedding the Sentry dynamic library.

**Size**

The archive is slightly smaller with mergeable enabled, but the installed app should be slightly larger because of additional metadata.

| Default | Mergeable |
| ------- | ----------- |
|  Bildschirmfoto 2024-08-26 um 16 06 41 | Bildschirmfoto 2024-08-26 um 16 06 35 |

**Launch Time**

Load times are similar. Launched both versions 10 times after the initial installation. Launching from Xcode takes longer when using `mergeable` instead of the default dylib.

| Default | Mergeable |
| ------- | ----------- |
| app_launch_time_2_dyn | app_launch_time_2_merged | 

**Conclusion**

We could add the linker flags to our build script for Sentry-Dynamic. Users can then decide if they want to use mergeable. This is opt-in for them, as the default is the same as before.

We can delete this PR afterwards.

## :bulb: Motivation and Context

Sample to test mergeable option. 

Relates to [#3719](https://github.com/getsentry/sentry-cocoa/issues/3719)

### CODE REVIEW

**Comment by kahest** [comment]
> The archive is slightly smaller with mergeable enabled, **but the installed app should be slightly larger** because of additional metadata.

Not sure I fully understand this - I see a difference of 1.6 MB vs. 116 KB, which is significant, but you're saying in a real-world installed app on a device it would be more than 116 KB?

**Comment by denrase** [comment]
@kahest The non-mergable has the frameworks folder, where the sentry framework is included (the folder size is not shown in the screenshot). The mergable has the sentry framework plus some metadata, so it should be slightly larger, at least thats how i understood the [documentation](https://developer.apple.com/documentation/xcode/configuring-your-project-to-use-mergeable-libraries#Create-a-pre-built-mergeable-library)

**Comment by brustolin** [comment]
> We can delete this PR afterwards

Can we make the changes to enable Mergeable Samples instead?

**Comment by denrase** [comment]
Closing in favor of #4367

**Pull request closed without merging**
