### PR TITLE
ref: Remove unused param in CrashReportConverter

### PR DESCRIPTION
**Pull request by philipphofmann**
## :scroll: Description

The parameter `stripCrashedStacktrace` is not used and can be removed.

## :bulb: Motivation and Context

We don't want to have unused parameters.

#skip-changelog

## :green_heart: How did you test it?
CI.

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

**Review by philipphofmann — COMMENTED** [review]
This is awesome 👏

**Review by philipphofmann — COMMENTED** [review]
Oh no again 🙈

**Review by philipphofmann — COMMENTED** [review]
Good job 👏

**Review by philipphofmann — COMMENTED** [review]
Ship it 🚢

**Review by marandaneto — APPROVED** [review]
Dev of the year 👏

**Pull request merged**
