### PR TITLE
fix: Remove all permission checks

### LINKED ISSUE #2527: Serialize permissions to disk
### Description

Save every permission change in the disk to be able to use it with crash reports.

### LINKED ISSUE #2528: Apps required to have NSLocationAlwaysAndWhenInUseUsageDescription
### Description

Apps get rejected from the app store because NSLocationAlwaysAndWhenInUseUsageDescription is missing despite not using locations on both 7.31.0 and 7.24.1. This is related to https://github.com/getsentry/sentry-cocoa/issues/2065.

We could consider removing checking for permissions in v 8.0.0. We rather don't report that data than being responsible for apps getting rejected from the app store.

If we remove the permissions, we should close https://github.com/getsentry/sentry-cocoa/issues/2527.

### PR DESCRIPTION
**Pull request by kevinrenskers**
## :scroll: Description

Remove the permissions. Not worth the risk of apps getting denied by Apple.

## :bulb: Motivation and Context

Closes #2528
Closes #2527

## :green_heart: How did you test it?

Removing code and making the tests pass again.

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [ ] No breaking changes

### CODE REVIEW

**Comment by brustolin** [comment]
Should we include a manual way to report permissions?

**Comment by kevinrenskers** [comment]
I think as long as we have any code in the SDK at all that deal with these permissions people will keep getting these review problems. So I don't think we can ship this feature at all, unless it becomes like a separate package / pod.

**Review by philipphofmann — APPROVED** [review]
LGTM, thank you @kevinrenskers 👍. Please add a short entry to https://github.com/getsentry/sentry-cocoa/tree/8.0.0/develop-docs#decision-log why we removed the permissions. It can be one sentence. Do we need to update the docs?

**Comment by kevinrenskers** [comment]
Done

**Comment by kevinrenskers** [comment]
> Do we need to update the docs

I'll see if we have anything about that feature in the docs, and if so, create a docs PR.

**Pull request merged**
