### PR TITLE
style: Change line length to 120

### PR DESCRIPTION
**Pull request by kevinrenskers**
We've had a discussion about line length back in early July. Philip likes 100, but both Dhiogo and I prefer longer lines. But we never reached a conclusion.

Opening this PR to get feedback, and to see how this impacts the code. To my eyes at first glance, the code really does look a LOT better with this change.

#skip-changelog

### CODE REVIEW

**Review by armcknight — CHANGES_REQUESTED** [review]
I'm not a fan of changing code and dirtying the git history just to change code style. I would prefer if we could roll this into https://github.com/getsentry/sentry-cocoa/pull/1841 so that only newly changed lines are subjected to code format.

**Comment by kevinrenskers** [comment]
I quite strongly disagree with that - then you end up with multiple code styles within the project - within the same file even. I'm curious - what is the problem of having one commit in the git history that changes the code style?

**Comment by armcknight** [comment]
The issue becomes that if you want to see why a line of code is doing a given thing or who made the change, being confronted with a history of nonfunctional changes means that out-of-the-box solutions in IDEs or on GitHub won't work as well, and you have to go on a wild goose chase to find the rationale behind the logic.

IMO it's more important to preserve a good documentation record that's easy to use, than to make nonfunctional changes across the codebase, or pull in unrelated code/files into changesets because they somehow wound up with wrong/outdated format on `master`.

**Comment by kevinrenskers** [comment]
Right, but most lines have many changes, so looking at the history you'll always have to look through multiple changes. I'm not sure if having one change in there that only changes the style is that big of a problem, compared to the benefit of making all the code easier to read. I'm curious what the rest of the team thinks.

**Comment by bruno-garcia** [comment]
> I'm not a fan of changing code and dirtying the git history just to change code style. I would prefer if we could roll this into https://github.com/getsentry/sentry-cocoa/pull/1841 so that only newly changed lines are subjected to code format.

The problem with this is that now you mix code changes with style changes (in the whole file) and makes reviewing code much harder.

I'd vouch for doing a single PR that changes the whole code base in one go.

**Comment by brustolin** [comment]
@kevinrenskers Can you fix the CI not passing?

**Comment by bruno-garcia** [comment]
All of that said, I'm not actively working on this code base so I'm leaving my opinion here.

**Comment by kevinrenskers** [comment]
> @kevinrenskers Can you fix the CI not passing?

It fails in "lint / No changes in high risk files". How would I make that pass? I think we kinda need to force this through.

**Comment by bruno-garcia** [comment]
> It fails in "lint / No changes in high risk files". How would I make that pass? I think we kinda need to force this through

I assume u need to update some snapshot file?

**Comment by kevinrenskers** [comment]
But merging this would then also update the snapshot file. But I don't think it's a snapshot file but just a list of file paths that are configured to not have any changes. Which makes sense when it's actual code changes, but in this case I would just merge if after reviewing those files. I'll look up that array of file paths.

**Comment by bruno-garcia** [comment]
We should fix this test to check against a file that can be changed in the PR (aka: snapshot). Instead of forcing merge with break checks

**Comment by brustolin** [comment]
> I assume u need to update some snapshot file?

We have a list (just one actually) of checksum and files to check against. 
The script itself has the instruction to update it.

@kevinrenskers  Just look for 'no-changes-in-high-risk-files.sh' file

**Comment by kevinrenskers** [comment]
Thanks! I I hadn't gotten around to looking into it yet, but I'm sure I would've found it as well. Nice solution with the checksum.

**Review by brustolin — APPROVED** [review]
LGTM

**Comment by kevinrenskers** [comment]
I can't merge while @armcknight has requested changes.

**Comment by brustolin** [comment]
@armcknight I don't mind having different files with different styles, but I think we should be consistent in the same file. As soon as any change to the file are needed, we must update the entire file. At least the changes will happen gradually. Will #1841 work this way? Is it ready to merge? Or how long do you need to finish it?

I also don't mind updating all at once. For me we just do it.

**Comment by bruno-garcia** [comment]
@armcknight any chance we can change your mind on this one? The benefits seems to outweigh the costs. Git blame will take it to the change before the one done by this PR, and you'll be able to leverage longer lines forever now on this code base.

**Comment by bruno-garcia** [comment]
@mitsuhiko is another staying on the argument of git history cost not being worth the extra length

**Comment by bruno-garcia** [comment]
Lets keep the width of a 1980's computer, fits Objective-C :sadcry:

**Comment by philipphofmann** [comment]
> Philip likes 100

I don't really care too much about code formatting. As long as it's automated and consistent, I'm fine with it.

**Pull request closed without merging**
