### PR TITLE
ci: Update default Xcode to 13.4.1

### PR DESCRIPTION
**Pull request by philipphofmann**
Fixes GH-2113

##skip-changelog

### CODE REVIEW

**Review by armcknight — APPROVED** [review]
LGTM. What was the deal with the hub test and catalyst?

**Review by armcknight — CHANGES_REQUESTED** [review]
Actually, I just noticed that there are a couple hardcoded paths to xcode 13.2 in integration-tests.yml and saucelabs-UI-tests.yml, do we need those updated too?

**Review by brustolin — APPROVED** [review]
LGTM

**Comment by armcknight** [comment]
Do we need this one too @philipphofmann? https://github.com/getsentry/sentry-cocoa/blob/master/.github/workflows/integration-tests.yml#L80

**Review by armcknight — APPROVED** [review]
Approving so you can merge when you need to but please see my last comment about `integration-tests.yml` @philipphofmann

**Pull request merged**
