### PR TITLE
Add more error checking to crash recording and reporting

### PR DESCRIPTION
**Pull request by patrickhartling**
We ran version 4.4.3 of the Sentry SDK through a code scanner, and it identified several unchecked error conditions, mostly related to memory allocation. This branch has my patches to address those items.

### CODE REVIEW

**Comment by fetzig** [comment]
Hi @patrickhartling.

 * why you need to check for NULL before calling free(something)? TTBOMK free(NULL) is fine.
 * the checks implemented in SentryCrashFileUtils.c seems to be inconsequential as well (while loop wouldn't be accessed anyways).

Can you provide failing tests that succeed after those changes?

**Comment by patrickhartling** [comment]
As far as I understood it, 

> Hi @patrickhartling.
> 
> * why you need to check for NULL before calling free(something)? TTBOMK free(NULL) is fine.

I thought so, too, but the code analyzer we use flags it as a flaw. If that change isn't something you're comfortable with, the other option I have is to submit this case back to the analyzer reporting tool as a false positive.

> * the checks implemented in SentryCrashFileUtils.c seems to be inconsequential as well (while loop wouldn't be accessed anyways).

I don't quite follow the reasoning there. Without the check for `NULL`, the `while` loop would be executed if `calloc(3)` returns `NULL` to indicate an error. That would lead to dereferencing `entryList` and a crash.

> Can you provide failing tests that succeed after those changes?

I don't know how to write a test that will cause `malloc(3)` and `calloc(3)` to return `NULL`. Do you have any pointers on how I might get started with that?

**Comment by fetzig** [comment]
First of all, thanks for your contribution. 

I get your point, but `SentryCrash` will in most cases not be patched without a "solid" reason. Solid would be, i.e. an actual reproducible crash.

The static analyzer result isn't enough reason to patch this. BUT maybe I missed a change you did that indeed fixes a (possible) crash. If so, please provide a unit test. Like those: https://github.com/getsentry/sentry-cocoa/tree/master/Tests/SentryTests

Have a look at the `SentryCrash` unit tests here: https://github.com/getsentry/sentry-cocoa/tree/master/Tests/SentryTests/SentryCrash

**Comment by patrickhartling** [comment]
@fetzig I've tried an approach of having a test exhaust the heap memory available to the process before calling in to some code with the additional error checking. The intent is to "force" `malloc(3)` to return `NULL` and thus trigger the new error handling. As you might guess, this does not work very well for a few reasons:

 * Depending on the machine, it can take a long time to consume the available memory (and roughly as much time to release it later). In other words, the test suite performance will plummet by adding just one such test.
 * The test suite and the Objective-C runtime in general do not function well when the heap is nearly or fully exhuasted. For example, I am seeing crashes when trying to tear down a single test when heap memory is constrained.
 * It's difficult/impossible to be certain that the desired `malloc(3)` call will fail and return `NULL`.

An alternative approach would be to alter the code to wrap `malloc(3)` and `calloc(3)` and use a custom implementation during testing. I am going to go ahead and assume that something so invasive to the code base would be unwelcome. These are the only two ideas I have for demonstrating what the additional error handling protects against.

At this point, I cannot offer any concrete evidence that my changes fix problems in the code. They add error checking for the edgiest of edge cases. That being said, the error checks are in line with plenty of other parts of the SentryCrash section of the code base. Nevertheless, if tests are required for this PR to be accepted, then this PR is going to have to be closed without merging.

**Comment by fetzig** [comment]
I will try and get at least 1 extra reviewer (and feedback) on this.

Thx again for your help.

**Comment by fetzig** [comment]
@patrickhartling could you describe which tool you used and how you configured it to analyze the code?

**Comment by patrickhartling** [comment]
@fetzig It's a third-party service that my company pays for. In the case of the team I'm on, the service scans an iOS application binary built with Bitcode enabled. I cannot speak to the configuration details as I do not have access to that. It's described as a "medium" level of security, at least as defined by the hosting company. That more or less translates into flaws that are deemed a high risk or a very high risk to security as being disallowed. I know that that is pretty vague, but I had a consultation meeting recently and got some insight. There were a couple of take-aways that pertain here:

 1. The scanner checks code against CVEs, and identifying (potentially) missing error handling is one of the more rudimentary things that it does. For C code in particular, it seems to lean heavily on assumptions about misusing `malloc(3)`, `strdup(3)`, and other functions that allocate heap memory.
 1. The scanner is, let's say, aggressive about evaluating branching. It will try the path of a branch even if there is no way that that that path could be executed. For example, if the code checks that `malloc(3)` returned `NULL` and takes an early out path from a method, the scanner tries the path as if that `NULL` check weren't there. I did not include any such changes in this branch and instead submitted those back as false positives.

In my personal opinion, the Xcode static analyzer is much better about identifying problems, especially subtle ones that require looking at more than successive instructions.

**Comment by fetzig** [comment]
@patrickhartling we are going to merge this PR. thanks for sharing your findings.

**Pull request merged**
