### PR TITLE
meta: migrate to XcodeGen and xcconfigs

### PR DESCRIPTION
**Pull request by armcknight**
See https://github.com/getsentry/sentry-cocoa/discussions/2024 for discussion on this task.

# Points of interest

- all xcodeproj, xcscheme and xcworkspace files have been removed from git tracking and are now .gitignore'd
- all targets from all previous projects will now be in a single project together (except SPM/Carthage based projects: Carthage-Validation, macOS-SPM-CommandLine, test-server)
- the previously multiplatform targets Sentry and SentryTests now are one target per platform
- the project spec itself: `//project.yml`
- code signing is now set to automatic by default, and is only swapped for match-managed creds in CI (see `Fastfile`)
- new makefile task to generate the project from the XcodeGen spec
- new xcconfigs in `//xcconfig/`

# TODO

- [x] Some files are committed to this branch to help keep track of intermediate results and checks when rebasing to keep up with `master`; they must be removed before merging this PR:
    - `//xcodebuild...` directories
    - //scripts/output-all-schemes-showbuildsettings.sh
- [x] update `//develop-docs/README.md`
- [x] update `//CONTRIBUTING.md`

#skip-changelog

### CODE REVIEW

**Comment by brustolin** [comment]
Can we have the group organisation as it was before?

New project file structure:
image

**Comment by brustolin** [comment]
Can we remove line 7 from MAKEFILE?
```
cd Samples/TrendingMovies && carthage update --use-xcframeworks
```

It makes init unnecessary long f0r SDK development.

**Comment by kevinrenskers** [comment]
> Can we have the group organisation as it was before?
> 
> New project file structure: image

I would say that is pretty much a must-have.

**Comment by kevinrenskers** [comment]
So how would you add a new file to the project after this change? I am guessing you can't do it from within Xcode anymore?

**Comment by brustolin** [comment]
Can we have these less used files at the bottom of the file tree?
Maybe put Sources and Tests on top?

Screenshot 2022-08-08 at 09 50 21

**Comment by kevinrenskers** [comment]
> Can we have these less used files at the bottom of the file tree? Maybe put Sources and Tests on top?

Do we even need to see all those files like the dotfiles, Makefile, LICENSE, README, fastlane, develop-docs etc etc?

**Comment by brustolin** [comment]
> So how would you add a new file to the project after this change? I am guessing you can't do it from within Xcode anymore?

If they are source files (.m, .h) you can create them from Xcode, no need of extra work.

But we lost the ability to configure any part of the project using the IDE. For me this is a downside.

**Comment by kevinrenskers** [comment]
For me a huge huge downside (a dealbreaker really) is that we now have one huge list of files in Xcode. We could create folders on disk and organize them that way, but then we'll no doubt run into problems with the header files which need to be in specific `public` or `include` folders, so would no longer appear alongside the .m file.

**Comment by bruno-garcia** [comment]
We have a discussion happening in two places now. Should we move this to:

https://github.com/getsentry/sentry-cocoa/discussions/2024#discussioncomment-3350456 ?

If so, folks could copy messages from here and create a thread there. And delete the messages here.

**Comment by armcknight** [comment]
@brustolin I created a separate [issue](https://github.com/getsentry/sentry-cocoa/issues/2053) for this since it's already on `master`: https://github.com/getsentry/sentry-cocoa/pull/2025#issuecomment-1207772947

**Comment by armcknight** [comment]
I'm going to work on reorganizing the actual file/folder structure to match what the project currently looks like on `master`: 
image

**Comment by philipphofmann** [comment]
Just curious, why did you close this @armcknight?

**Pull request closed without merging**
