### PR TITLE
fix: nxgetlocalarch app store for mac

### PR DESCRIPTION
**Pull request by bruno-garcia**
Alternative with #ifdef

No so sure about this fix since the compile flag value seems inverted, unless I'm missing something.
I've tested on mac and iOS and it worked though.

Will leave this here to be discussed when @HazAT and @philipphofmann are online

### CODE REVIEW

**Comment by philipphofmann** [comment]
I don't see `NXGetLocalArchInfo` being marked as private in `mach-o/arch.h`. As suggested in https://github.com/firebase/firebase-ios-sdk/issues/6128#issuecomment-664525622 for me it also seems there could be a problem with Apple's symbol scanner. As mentioned in https://github.com/getsentry/sentry-cocoa/issues/635 the user could upload the iOS version, but only had trouble with the macOS version of his app. Also in https://github.com/firebase/firebase-ios-sdk/issues/6128 the user had trouble with Mac Catalyst. So maybe we should only disable the call to `NXGetLocalArchInfo` for macOS or we just wait until Apple fixes the problem on their side.

**Comment by bruno-garcia** [comment]
> So maybe we should only disable the call to NXGetLocalArchInfo for macOS or we just wait until Apple fixes the problem on their side.

Agree that would be best

**Comment by philipphofmann** [comment]
> > So maybe we should only disable the call to NXGetLocalArchInfo for macOS or we just wait until Apple fixes the problem on their side.
> 
> Agree that would be best

Do you agree with waiting or only disabling with macOS?

**Comment by bruno-garcia** [comment]
Disabling only on a Mac which this PR tries to do seems like the way to go

**Comment by bruno-garcia** [comment]
Closing as arch is reported currently (at least on iOS emulator)

**Pull request closed without merging**
