### PR TITLE
feat: track network connectivity changes with breadcrumbs

### PR DESCRIPTION
**Pull request by armcknight**
## :scroll: Description

Monitor reachability of https://sentry.io in SentryBreadcrumbTracker and have its delegate record a breadcrumb every time connectivity changes, recording its description in the breadcrumb data.

Currently calling this breadcrumb type "connectivity", which we'd need to add to https://develop.sentry.dev/sdk/event-payloads/breadcrumbs/#breadcrumb-types. This is subject to change, as is the breadcrumb category of "device.connectivity".

Refactors:
- access SentryReachability via SentryDependencyContainer
- expose description constants eg SentryConnectivityCellular

## :bulb: Motivation and Context

For #3127 

## :green_heart: How did you test it?

New test case in [SentryBreadcrumbTrackerTests.swift](https://github.com/getsentry/sentry-cocoa/pull/3232#diff-71bf2f79c889d0d67bbf02fcb001e02cb392e36c511ca8d1b8f67afa656470ec).

### CODE REVIEW

**Comment by stefanosiano** [comment]
On Android the breadcrumbs have:
type: `system`
category: `network.event`
`data["action"]`: one of `NETWORK_AVAILABLE`, `NETWORK_LOST`, `NETWORK_CAPABILITIES_CHANGED`

We already collect other breadcrumbs under the `system` type, coming from the system, like temperature, phone state and other generic system events.
I'm updating the meta issue with this info. 
I'm not sure if develop docs are to be updated, as these really affect only mobile SDKs, but perhaps it's a good idea anyway, since i didn't find the `system` type documented anywhere, either.

**Comment by armcknight** [comment]
Thanks @stefanosiano for the info! Let me know anything I can do to help update docs, even if you just need a review ✨

**Comment by armcknight** [comment]
I just noticed that much of the relevant implementation of SentryReachability are static singleton states, so instantiating another one and calling `-[monitorURL:usingCallback:]` will erase the previous monitoring setup by our internal networking stack. This will require more refactoring.

**Review by brustolin — COMMENTED** [review]
Code wise looks good, but CI is broken

**Review by brustolin — APPROVED** [review]
LGTM

**Comment by armcknight** [comment]
@brustolin I pushed a new commit that refactors a couple things:
- allows multiple observers to watch reachability changes
- internalize the URL used to monitor network state
- don't ignore the first reachability callback, as it contains useful information (like, in the happy path, that the network is reachable as of the time monitoring started)
- simplify several flows, including rearranging code in reachability functions to use early exits

**Review by brustolin — APPROVED** [review]
All good with the changes.

**Pull request merged**
