### PR TITLE
Remove invalid excludes from Package.swift

### PR DESCRIPTION
**Pull request by JonathanDowning**
## :scroll: Description

Xcode 13 now shows issues with packages in the issue navigator.
A few issues popped up for this SDK, namely that there is are invalid excludes in the Package.swift, this PR removes them.

## :bulb: Motivation and Context

This removes warnings from the Xcode 13 issue navigator

## :green_heart: How did you test it?

N/A

## :pencil: Checklist

- [ ] I reviewed the submitted code
- [ ] I added tests to verify the changes
- [ ] I updated the docs if needed
- [ ] Review from the native team if needed
- [x] No breaking changes

### CODE REVIEW

**Review by bruno-garcia — APPROVED** [review]
Thanks @JonathanDowning !

**Comment by bruno-garcia** [comment]
Did it warn also about `Samples` and `Tests` though? Those exist.
It makes sense to let them flow through though.

**Comment by philipphofmann** [comment]
Thanks, @JonathanDowning!

**Comment by JonathanDowning** [comment]
> Did it warn also about `Samples` and `Tests` though? Those exist.
> It makes sense to let them flow through though.

Thanks for merging!
Indeed it does @bruno-garcia 
Screen Shot 2021-06-15 at 08 08 44

**Comment by noisypigeon** [comment]
When will this be available on a published release? Thanks!

**Comment by philipphofmann** [comment]
> When will this be available on a published release? Thanks!

@noisypigeon, this is published since 7.2.0-beta.2. We plan to have GA 7.2.0 still in July, but I can't guarantee that.

**Comment by noisypigeon** [comment]
Thanks for the update!

**Pull request merged**
