### PR TITLE
fix: flaky tests in CI

### PR DESCRIPTION
**Pull request by armcknight**
By chance I noticed one of the tests flaking uses notifications ([here](https://github.com/getsentry/sentry-cocoa/runs/7980265032?check_suite_focus=true#step:9:1410)), so wanted to try fixing all of them by adding XCTExpectations/waits for them to post before proceeding with assertions.

The temp commit forces them to run 50 times in both xcode 12/13, hopefully that would fail at least a couple times if this doesn't fix the flakiness.

Possibly fixes https://github.com/getsentry/sentry-cocoa/issues/2062

#skip-changelog

### CODE REVIEW

**Comment by armcknight** [comment]
There's a compilation failure that led me to discovering some dead code, fixing that up and reworking some conditional compilation based on platform...

**Comment by armcknight** [comment]
Running just the flaky test cases 50 times without a failure, maybe this is the fix https://github.com/getsentry/sentry-cocoa/runs/7982082603?check_suite_focus=true

**Comment by armcknight** [comment]
OK so that didn't work: https://github.com/getsentry/sentry-cocoa/runs/7982225398?check_suite_focus=true

Looking at what tests run before it that may leave dirtied state that corrupts these tests.

**Comment by philipphofmann** [comment]
@armcknight, what is the current state of this PR? Do you need any input?

**Comment by armcknight** [comment]
@philipphofmann I'm stumped here currently, haven't circled back to look at what state could be getting corrupted before these tests run.

**Comment by philipphofmann** [comment]
I don't understand why the tests fail in CI and not locally. If the state would be a real problem, the tests should also fail locally sometimes.

**Comment by armcknight** [comment]
Closing this as I haven't had time to look at it. Can always resurrect the effort later.

**Pull request closed without merging**
