### PR TITLE
Tick allow-app-extension-API-only box

### PR DESCRIPTION
**Pull request by mxcl**
Prevents Carthage warning.

### CODE REVIEW

**Comment by mxcl** [comment]
Per chance are the precompiled binaries built in a special way? Because they didn't seem to get this check-box. I still get the warning.

**Comment by HazAT** [comment]
@mxcl I forgot to tick it in the other project as well, will make a new release today and ping you.
Sorry about that.

**Comment by mxcl** [comment]
Oh, my bad. Should have seen there were other places I needed to do this.

**Comment by HazAT** [comment]
@mxcl `3.8.4` is released with the fix 👍

**Comment by mxcl** [comment]
Works! Appreciated x

**Pull request merged**
